https://www.perplexity.ai/search/0638400d-59de-4d83-8e38-0cb807daf590

In [2]:
import numpy as np
from numpy import ndarray

my_array:ndarray = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time 

for _ in range(10):
    #list的comprehension,list綜合表達式
    my_lists = [x*2 for x in my_list]

CPU times: user 2 μs, sys: 1 μs, total: 3 μs
Wall time: 5.25 μs


In [4]:
%time for _ in range(10): my_array2 = my_array * 2

CPU times: user 4.56 ms, sys: 3.81 ms, total: 8.37 ms
Wall time: 8.34 ms


In [5]:
#tuple,1個元素的表示法
(4, 5)
type((4,))

tuple

In [6]:
np.array(range(4)).shape

(4,)

50個學生，每個學生有50個分數，每個分數50~100個學生，每個學生有50個分數，每個分數50~100

In [7]:
np.random.seed(42)
scores = np.random.randint(50, 101,(50,5))
scores

array([[ 88,  78,  64,  92,  57],
       [ 70,  88,  68,  72,  60],
       [ 60,  73,  85,  89,  73],
       [ 52,  71,  51,  73,  93],
       [ 79,  87,  51,  70,  82],
       [ 61,  71,  93,  74,  98],
       [ 76,  91,  77,  65,  64],
       [ 96, 100,  93,  52,  86],
       [100,  56,  70,  58,  88],
       [ 67,  53,  74,  63,  99],
       [ 58,  75,  51,  69,  77],
       [ 96,  56,  93,  57,  96],
       [ 84,  63,  66,  85,  99],
       [ 89,  53,  51,  55,  91],
       [ 53,  78,  67,  75,  93],
       [ 83,  59,  85,  63,  80],
       [ 97,  64,  57,  63,  72],
       [ 89,  70,  65,  94,  67],
       [ 96,  73,  75,  74,  94],
       [ 90,  78,  64,  94,  50],
       [ 74,  56,  58,  73,  50],
       [ 93,  57,  73,  60, 100],
       [ 66,  57,  84,  84,  82],
       [ 54,  91,  88,  90,  77],
       [ 56,  58,  57,  61,  83],
       [ 82,  97,  72,  73,  86],
       [ 84,  93,  89,  71,  76],
       [ 84,  50,  84,  86,  96],
       [ 63,  52,  50,  54,  75],
       [ 63,  

In [8]:
#ndarray常用的實體屬性
scores.ndim
scores.shape
scores.size
scores.dtype

dtype('int64')

基本索引和分割
 - ndarray[index]
 - ndayyay[start:end:step]

In [9]:
#2維
scores[0][4] #類似list的操作
scores[0, 4] #ndarrya的slice的操作法

np.int64(57)

In [10]:
## 取得第1位學生的分數
scores[0] #shape(5,)
scores[0,:] #shape(5,0)
scores[0:1,:] #shape(1,5)

array([[88, 78, 64, 92, 57]])

In [11]:
## 取得第1,2位學生的分數
scores[:2]
scores[:2,:]
scores[(0,1),:]

array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60]])

In [12]:
## 取得第1,2,5位學生的分數
scores[(0,1,4),:]

array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60],
       [79, 87, 51, 70, 82]])

In [ ]:
## 取得第1科的所有分數
scores[:,0] #(50,)
scores[:,0:1] #(1,50)

In [ ]:
## 取得第1,2科的所有分數
scores[:,:2] #(50,2)

In [ ]:
## 取得前30位學生的最後3科分數
scores[:30,-3:] #(30,3)